apps/grain_web/lib/grain_web/router.ex
defmodule GrainWeb.Router do
  use GrainWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    # plug :fetch_live_flash
    # plug :put_root_layout, {GrainWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GrainWeb do
    pipe_through :browser
    # live "/", PageLive, :index
    get "/", PageController, :index
    get "/grains", GrainController, :inde
    get "/grain", GrainController, :index
    get "/home", HomeController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", GrainWeb do
  #   pipe_through :api
  # end
  if Mix.env() in [:dev, :test, :prod] do
    import Phoenix.LiveDashboard.Router
    import Plug.BasicAuth

    pipeline :admins_only do
      plug :basic_auth, username: "admin", password: "13579"
    end

    scope "/" do
      pipe_through [:browser, :admins_only]
      live_dashboard "/dashboard", metrics: GrainWeb.Telemetry, ecto_repos: [Grain.Repo]
    end
  end
end

apps/grain_web/lib/grain_web/controllers/grain_controller.ex
defmodule GrainWeb.GrainController do
  use GrainWeb, :controller
  alias Grain.Grains, as: Gg

  def inde(conn, params) do
    params =
      if params == %{} do
        %{
          "page" => "",
          "year" => "",
          "city1" => "",
          "city2" => "",
          "city3" => "",
          "limit" => "",
          "page_num" => ""
        }
      else
        params
      end

    {:ok, pid} = Agent.start_link(fn -> 0 end)

    page_num =
      if params["page_num"] in ["", nil] do
        1
      else
        String.to_integer(params["page_num"])
      end

    {g, grains} = Gg.search_grain(params)
    render(conn, "inde.html", g: g, grains: grains, params: params, pid: pid, page_num: page_num)
  end

  def index(conn, params) do
    grains =
      if Map.has_key?(params, "td_data") && params["td_data"] != "" do
        [x, y] = params["td_data"] |> String.split(",")
        Gg.grains_list(x, y)
      else
        if Map.has_key?(params, "search") do
          Gg.search_grains(params["search"])
        else
          Gg.list_grains()
        end
      end

    {:ok, pid} = Agent.start_link(fn -> 0 end)
    render(conn, "index.html", grains: grains, pid: pid)
  end
end

apps/grain_web/lib/grain_web/controllers/home_controller.ex
defmodule GrainWeb.HomeController do
  use GrainWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/grain_web/lib/grain_web/controllers/page_controller.ex
defmodule GrainWeb.PageController do
  use GrainWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/grain_web/lib/grain_web/views/error_view.ex
defmodule GrainWeb.ErrorView do
  use GrainWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  def render("404.html", _assigns) do
    "网站正在开发中,联系电话：13581243756"
  end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/grain_web/lib/grain_web/views/grain_view.ex
defmodule GrainWeb.GrainView do
  use GrainWeb, :view
  import Phoenix.HTML.Tag

  def the_begin_page(page_num) do
    page_num
  end

  def limit(params) do
    if params["limit"] in ["", nil] do
      50
    else
      String.to_integer(params["limit"])
    end
  end

  def url(num, params) do
    "/grains?page=#{num}&limit=#{params["limit"]}&city1=#{params["city1"]}&city2=#{
      params["city2"]
    }&city3=#{params["city3"]}&year=#{params["year"]}&page_num=#{params["page_num"]}&bool=#{
      params["bool"]
    }"
  end

  def the_up_page(params) do
    page_num = String.to_integer(params["page_num"])

    "/grains?page=#{page_num - 10}&limit=#{params["limit"]}&city1=#{params["city1"]}&city2=#{
      params["city2"]
    }&city3=#{params["city3"]}&year=#{params["year"]}&page_num=#{page_num - 10}&bool=#{
      params["bool"]
    }"
  end

  def the_next_page(page_num, params) do
    "/grains?page=#{page_num + 10}&limit=#{params["limit"]}&city1=#{params["city1"]}&city2=#{
      params["city2"]
    }&city3=#{params["city3"]}&year=#{params["year"]}&page_num=#{page_num + 10}&bool=#{
      params["bool"]
    }"
  end

  def name(redis) do
    a =
      if redis.store_no != nil do
        if String.match?(redis.store_no, ~r/仓/) do
          ""
        else
          "仓"
        end
      end

    raw("#{redis.storage_depot_name}</br>#{redis.store_no}#{a}</br>#{redis.request_no}")
  end

  def dizeng(pid) do
    Agent.update(pid, fn i -> i + 1 end)
    Agent.get(pid, fn i -> i end)
  end

  def limit_num(num, params) do
    if params["limit"] in ["", nil] do
      ceil(num / 50)
    else
      ceil(num / String.to_integer(params["limit"]))
    end
  end
end

apps/grain_web/lib/grain_web/views/home_view.ex
defmodule GrainWeb.HomeView do
  use GrainWeb, :view
end

apps/grain_web/lib/grain_web/views/layout_view.ex
defmodule GrainWeb.LayoutView do
  use GrainWeb, :view
end

apps/grain_web/lib/grain_web/views/page_view.ex
defmodule GrainWeb.PageView do
  use GrainWeb, :view
end

apps/grain_web/lib/grain_web/templates/grain/inde.html.eex
<div>
<!--<h5><a href="https://www.youmile.vip">点击进入长虹米厂官网</a></h5>--!>
  <h3>稻谷历史交易记录</h3>
  <!--<h4>欢迎同行交流：13581243756 微信同号</h4>--!>
  <%= form_for @conn,Routes.grain_path(@conn, :inde),[method: :get] ,fn f -> %>
    <div>
    <label for="">已交易城市1（例如“九江”）</label>
    <%= text_input f, :city1 %>
    <%= label f,"城市2" %>
    <%= text_input f, :city2 %>
    <%= label f,"城市3" %>
    <%= text_input f, :city3 %>
    <%= label f, "年份"%>
    <%= text_input f, :year %>
    <%= label f, "显示已成交" %>
    <%= checkbox(f, :bool) %>
    <%= label f, "每页行数" %>
    <%= text_input f, :limit %>
    <%= submit "查询", class: "submit" %>
    </div>
    <table class="qgg-table">
    <thead>
      <tr>
      <!--<td>编号</td>--!>
        <td>交易时间</td>
        <td>交货地址</td>
        <td>稻谷信息</td>
        <!--<td>类型</td>
        <td>品种</td>
        <td>等级</td>
        <td>年份</td>
        <td>交易数量</td>--!>
        <td>起始价格</td>
        <td>最终价格</td>

      </tr>
    </thead>
    <tbody>
      <%= for redis <- @grains do %>
        <tr>
        <!--<td><%= dizeng(@pid) %></td>--!>
          <td><%= redis.inserted_at |> Timex.to_datetime("Etc/UTC") |> Timex.to_datetime("Asia/Shanghai") |> DateTime.to_naive %></td>
          <td><%= name(redis) %></td>
          <td><%= redis.mark_number %></br><%= redis.trantype %>: <%= redis.year %>年 <%= redis.grade %> <%= redis.variety %> <%= redis.trade_amount %>吨</td>
          <!--<td><%= redis.variety %></td>
          <td><%= redis.grade %></td>
          <td><%= redis.year %></td>
          <td><%= redis.trade_amount %></td>--!>
          <td><%= redis.starting_price %></td>
          <td><%= redis.latest_price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<nav class="pagination">
   <%= for x <- the_begin_page(@page_num)..(the_begin_page(@page_num) + 9) do %>
     <%= if x <= limit_num(@g,@params) do %>
       <a href=<%= url(x,@params) %>><%= x %></a>
     <% end %>
  <% end %>
  <%= if @page_num > 10 do %>
  <nav><a href=<%= the_up_page(@params) %>>上一页</a></nav>
  <% end %>
  <%= if ((the_begin_page(@page_num) + 9) * limit(@params)) < @g do %>
    <nav><a href=<%= the_next_page(@page_num,@params) %>>下一页</a></nav>
  <% end %>
  <span>总共<%= @g %>条数据</span>
</nav>
</div>

apps/grain_web/lib/grain_web/templates/grain/index.html.eex
<script charset="utf-8">
  function submitForm(t, tt='zeng'){
    let form = document.getElementById("myform")
    document.getElementById("td_data").value = [t.innerHTML, tt]
    form.submit()
} 
</script>
<div>
  <h5><a href="https://www.youmile.vip">点击进入长虹米厂官网</a></h5>
  <h3>稻谷历史交易记录</h3>
  <%= form_tag Routes.grain_path(@conn, :index), [id: "myform", method: :get] do %>
    <div>
    <label for="">查询已交易粮库（例如“九江”）</label>
    <input type="text" value="" name="search"/>
    <input type="submit" value="搜索">
    </div>
    <table class="qgg-table">
    <thead>
      <tr>
        <td>编号</td>
        <td>交易时间</td>
        <td>交货地址</td>
        <td>类型</td>
        <td>
          品种
          <!--
          <select>
            <option value="品种">品种</option>
            <option value ="中晚籼稻">中晚籼稻</option>
            <option value="晚籼稻">晚籼稻</option>
            <option value="早籼稻">早籼稻</option>
            <option value="粳稻">粳稻</option>
            <option value="玉米">玉米</option>
            <option value="大豆">大豆</option>
            <option value="混合麦">混合麦</option>
          </select>
          <!-- </form> -->
        </td>
        <td>等级</td>
        <td>年份</td>
        <td>交易数量</td>
        <td>起始价格</td>
        <td>最终价格</td>

      </tr>
    </thead>
    <tbody>
      <%= for redis <- @grains do %>
        <tr>
          <td><%= dizeng(@pid) %></td>
          <td><%= redis.inserted_at |> Timex.to_datetime("Etc/UTC") |> Timex.to_datetime("Asia/Shanghai") |> DateTime.to_naive %></td>
          <td onclick=submitForm(this,"address")><%= redis.address <> "(#{redis.mark_number})" %></td>
          <td><%= redis.trantype %></td>
          <td onclick=submitForm(this,"variety")><%= redis.variety %></td>
          <td><%= redis.grade %></td>
          <td onclick=submitForm(this,"year")><%= redis.year %></td>
          <td><%= redis.trade_amount %></td>
          <td onclick=submitForm(this,"starting_price")><%= redis.starting_price %></td>
          <td onclick=submitForm(this,"latest_price")><%= redis.latest_price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <input type="hidden" name="td_data" id="td_data" value="" />
<% end %>
</div>

apps/grain_web/lib/grain_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?f83dbd7c07aaecd62e8bb1b7b9a0f7b7";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!--<title>黄梅县长虹米厂（优米乐生态农业）</title>--!>
    <!--<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <main role="main" class="container">
    <%= @inner_content %>
    </main>
    <footer>
      <p>copyright <a href="https://youmile.youhaovip.com" target="_blank">Zeng</a> <%= DateTime.utc_now.year %></p>
      <!--<script charset="gbk" src="http://www.baidu.com/js/opensug.js"></script>-->
    </footer>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script type="text/javascript" src="https://js.users.51.la/19821413.js"></script>
  </body>
</html>

apps/grain_web/lib/grain_web/templates/page/index.html.eex
  <form style="" action="http://www.baidu.com/baidu" target="_blank">
    <table><tr><td>
        <input name="tn" type="hidden" value="baidu">
        <a href="http://www.baidu.com/"><img src="http://img.baidu.com/img/logo-80px.gif" alt="Baidu" align="bottom" border="0"></a>
        <input style="background-color:#CCE8CF" type="text"  name="word" size="55" baiduSug="1">
        <input style="background-color:#CCE8CF" type="submit"  value="百度搜索">
    </td></tr></table>
  </form>
<header>
  <nav>
    <a target='_blank' href="http://www.hao123.com">hao123</a>
    <a target='_blank' href="http://hao.360.cn">360</a>
    <a id='a_red' target='_blank' href="https://youmile.herokuapp.com/home/grain_home">九江交易</a>
    <a id='q_red' target='_blank' href="http://www.ex-grain.cn/">谷物网</a>
    <a target='_blank' href="https://ruby-china.org/topics/">RubyChina</a>
    <a target='_blank' href="http://linuxeden.com/">Linuxeden</a>
  </nav>
  <nav>
    <a target='_blank' href="http://www.iqiyi.com/">爱奇艺</a>
    <a target='_blank' href="http://www.ifeng.com/">凤凰网</a>
    <a target='_blank' href="http://www.taobao.com/">淘宝网</a>
    <a id='w_red' target='_blank' href="http://www.grainmarket.com.cn/">稻谷公告</a>
    <a target='_blank' href="https://grain.gigalixirapp.com/grains">国家交易</a>
    <a id='q_red' target='_blank' href="http://123.127.88.167:8888/tradeClient/observe.html">粮食交易</a>
  </nav>
  <nav>
    <a target='_blank' href="http://www.padrinorb.com/">Padrino</a>
    <a target='_blank' href="http://cnbeta.com/">CnBeta</a>
    <a target='_blank' href="http://v2ex.com/">V2ex</a>
    <a target='_blank' href="http://qq.com">QQ</a>
    <a id='q_red' target='_blank' href="http://www.hbgrain.com/">湖北粮网</a>
    <a target='_blank' href="http://products.weather.com.cn/product/radar/index/procode/JC_RADAR_AZ9792_JB.shtml">天气预报</a>
  </nav>
  <nav>
    <a target='_blank' href="http://www.tmall.com/">天猫</a>
    <a target='_blank' href="http://www.hao123.com/jtwzcx">交通违章</a>
    <a target='_blank' href="http://news.sina.com.cn/">新浪新闻</a>
    <a target='_blank' href="http://36kr.com/">36kr</a>
    <a target='_blank' href="http://ditu.google.cn/">地图</a>
    <a target='_blank' href="http://www.sinatrarb.com/">Sinatra</a>
  </nav>
  <nav>
    <a target='_blank' href="http://www.mtime.com/">时光网</a>
    <a target='_blank' href="http://www.baidu.com/s?wd=%E4%B8%AD%E9%80%9A%E5%BF%AB%E9%80%92&rsp=6&f=1&oq=zto&tn=sitehao123&ie=utf-8&rsv_ers=xn1&rs_src=0">中通快递</a>
    <a target='_blank' href="http://www.ubuntu-china.cn/">Ubuntu</a>
    <a target='_blank' href="http://www.hotmail.com/">Hotmail</a>
    <a target='_blank' href="http://www.gmail.com/">Gmail</a>
    <a target='_blank' href="http://bbs.cnhubei.com/forum-3-1.html">中部崛起</a>
  </nav>
  <nav>
    <a target='_blank' href="http://17ce.com/">17ce</a>
    <a target='_blank' href="http://openhome.cc/Gossip/JavaScript/index.html">Javascript</a>
    <a target='_blank' href="http://openhome.cc/Gossip/Ruby/">Ruby</a>
    <a target='_blank' href="http://sequel.jeremyevans.net/">Sequel</a>
    <a target='_blank' href="https://newrelic.com/">Newrelic</a>
    <a target='_blank' href="https://id.heroku.com/login">Heroku</a>
  </nav>
  <nav>
    <a target='_blank' href="https://c9.io/web/login">C9</a>
      <a target='_blank' href="http://www.iyiou.com/">亿欧网</a>
      <a target='_blank' href="http://devdocs.io/">Devdocs</a>
      <a target='_blank' href="https://bitbucket.org/account/signin/">Bitbucket</a>
      <a target='_blank' href="https://github.com/login">Github</a>
      <a target='_blank' href="http://dict.cn/">词典</a>
  </nav>
</header>